import React, { useState } from 'react';
import {
  Mail,
  Send,
  MessageSquare,
  User,
  CheckCircle2,
  FileText,
  Download,
  HelpCircle,
  ChevronDown
} from 'lucide-react';

export const ContactSection: React.FC = () => {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });
  const [submitted, setSubmitted] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.email || !formData.message) return;
    setSubmitted(true);
  };

  const faqs = [
    {
      q: 'Is Security Testing legal to perform on any website?',
      a: 'NO. Performing security tests or vulnerability scans on systems without explicit written permission is illegal. Always practice on authorized staging environments, local containers, or bug bounty targets with published rules of engagement.'
    },
    {
      q: 'What is the difference between Black-box, White-box, and Gray-box testing?',
      a: 'Black-box testing is done with zero prior knowledge of internal source code. White-box testing provides full access to source code and architecture diagrams. Gray-box testing provides partial access (such as user credentials or API documentation).'
    },
    {
      q: 'What is OWASP Top 10?',
      a: 'The OWASP Top 10 is a standard awareness document for developers and web application security representing a broad consensus on the most critical security risks to web applications.'
    }
  ];

  const handleDownloadCheatSheet = () => {
    const text = `SECURITY TESTING BASICS - QUICK CHEAT SHEET FOR DEVELOPERS

1. SQL INJECTION (SQLi)
   - Rule: Always use Parameterized Queries (Prepared Statements) or ORMs.
   - Never concatenate raw user strings into SQL queries.

2. CROSS-SITE SCRIPTING (XSS)
   - Rule: Sanitize and context-encode all output before rendering in HTML.
   - Set HttpOnly flags on session cookies.

3. CROSS-SITE REQUEST FORGERY (CSRF)
   - Rule: Enforce SameSite=Strict cookies and validate Anti-CSRF tokens on state-changing POST/PUT requests.

4. AUTHENTICATION & SESSIONS
   - Rule: Use Argon2 / bcrypt for password hashing.
   - Enforce MFA and rate limiting on login endpoints.

5. INPUT VALIDATION
   - Rule: Validate type, length, and format using schema libraries (e.g. Zod).

Generated by Security Testing Basics Educational Platform.
`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Security-Testing-CheatSheet.txt';
    a.click();
  };

  return (
    <section id="contact" className="py-16 sm:py-20 bg-slate-950 relative border-t border-white/5">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        
        {/* Section Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="w-1.5 h-6 bg-blue-500 rounded-full" />
            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
                Contact & Student Resources
              </h2>
              <p className="text-xs sm:text-sm text-slate-400 mt-1">
                Have questions or need security testing reference materials? Reach out or download our cheat sheet
              </p>
            </div>
          </div>
          <span className="text-xs font-mono px-3 py-1 rounded bg-blue-500/10 border border-blue-500/20 text-blue-400 uppercase tracking-widest hidden sm:inline-block">
            Course Module 09
          </span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Contact Form Column */}
          <div className="lg:col-span-7 p-6 sm:p-8 rounded-3xl bg-slate-900 border border-white/5 shadow-2xl space-y-6">
            <div className="flex items-center justify-between border-b border-white/5 pb-4">
              <h3 className="text-xl font-bold text-white flex items-center gap-2">
                <MessageSquare className="w-5 h-5 text-blue-400" />
                Send Inquiry or Feedback
              </h3>
              <span className="text-xs font-mono text-slate-400">Response within 24h</span>
            </div>

            {!submitted ? (
              <form onSubmit={handleSubmit} className="space-y-4">
                {/* Name */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold font-mono text-slate-300 flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5 text-blue-400" /> Full Name
                  </label>
                  <input
                    type="text"
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="Jane Doe"
                    className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-white/5 text-slate-200 text-sm focus:border-blue-500 focus:outline-none"
                    id="contact-name-input"
                  />
                </div>

                {/* Email */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold font-mono text-slate-300 flex items-center gap-1.5">
                    <Mail className="w-3.5 h-3.5 text-blue-400" /> Email Address
                  </label>
                  <input
                    type="email"
                    required
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="student@university.edu"
                    className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-white/5 text-slate-200 text-sm focus:border-blue-500 focus:outline-none"
                    id="contact-email-input"
                  />
                </div>

                {/* Message */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold font-mono text-slate-300 flex items-center gap-1.5">
                    <MessageSquare className="w-3.5 h-3.5 text-blue-400" /> Message
                  </label>
                  <textarea
                    required
                    rows={4}
                    value={formData.message}
                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                    placeholder="Ask a question or request a security topic..."
                    className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-white/5 text-slate-200 text-sm focus:border-blue-500 focus:outline-none resize-none"
                    id="contact-message-input"
                  />
                </div>

                <button
                  type="submit"
                  className="w-full py-3.5 px-6 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-extrabold text-sm flex items-center justify-center gap-2 shadow-lg shadow-blue-900/30 cursor-pointer"
                  id="send-message-btn"
                >
                  <Send className="w-4 h-4" />
                  <span>Send Message</span>
                </button>
              </form>
            ) : (
              <div className="text-center py-8 space-y-4">
                <div className="w-16 h-16 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center justify-center mx-auto">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <h4 className="text-xl font-bold text-white">Message Sent Successfully!</h4>
                <p className="text-xs text-slate-300 max-w-sm mx-auto">
                  Thank you for reaching out, {formData.name}. We will get back to you shortly.
                </p>
                <button
                  onClick={() => {
                    setSubmitted(false);
                    setFormData({ name: '', email: '', message: '' });
                  }}
                  className="px-4 py-2 rounded-xl bg-slate-950 border border-white/5 text-xs font-mono text-blue-400 hover:text-white"
                >
                  Send Another Message
                </button>
              </div>
            )}
          </div>

          {/* Quick Resources & FAQs Column */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* Download Cheat Sheet Card */}
            <div className="p-6 rounded-3xl bg-slate-900 border border-white/5 shadow-xl space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-3 rounded-xl bg-slate-950 text-blue-400 border border-white/5">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-lg font-bold text-white">Developer Cheat Sheet</h4>
                  <p className="text-xs text-slate-400">Quick Reference Guide for Security Testing</p>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                Download a clean, printable text reference summarizing prevention guidelines for SQLi, XSS, CSRF, and authentication best practices.
              </p>

              <button
                onClick={handleDownloadCheatSheet}
                className="w-full py-3 px-4 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-blue-900/30"
                id="download-cheatsheet-btn"
              >
                <Download className="w-4 h-4" />
                <span>Download Security Cheat Sheet</span>
              </button>
            </div>

            {/* FAQs Accordion */}
            <div className="p-6 rounded-3xl bg-slate-900 border border-white/5 space-y-4">
              <h4 className="text-base font-bold text-white flex items-center gap-2">
                <HelpCircle className="w-4 h-4 text-blue-400" /> Frequently Asked Questions
              </h4>

              <div className="space-y-2">
                {faqs.map((faq, idx) => (
                  <div key={idx} className="rounded-2xl bg-slate-950 border border-white/5 overflow-hidden">
                    <button
                      onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                      className="w-full p-3.5 text-left text-xs font-bold text-slate-200 flex items-center justify-between gap-2 hover:text-blue-400 cursor-pointer"
                    >
                      <span>{faq.q}</span>
                      <ChevronDown className={`w-4 h-4 text-blue-400 transition-transform ${
                        openFaq === idx ? 'rotate-180' : ''
                      }`} />
                    </button>
                    {openFaq === idx && (
                      <div className="p-3.5 pt-0 text-xs text-slate-400 border-t border-white/5 leading-relaxed font-sans">
                        {faq.a}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
};
